### ISSUE TITLE
cooldowns with permissions are not working

### ISSUE THREAD

**Issue by cindyker** [andune/HomeSpawnPlus#35] opened 2015-02-05 01:57 UTC
http://paste.md-5.net/juvasahoba.sm
I have two permission groups I want to work with separate cool downs then the default one.
I am not sure what cooldownPerPermission means.

In order for the config to actually load I had to comment out the whole permissions section.

  permission:
    limit1:
      cooldownPerPermission: false
      resetOnDeath: true
      permissions:
        - group.patriot
        - groups.patriot
      home: 0
      home-named: 0
      sethome: 0
      sethome-named: 0
      spawn: 0
      spawn-named: 0
      groupspawn: 0
      homeinvitetp: 0

    limit2:
      cooldownPerPermission: false
      resetOnDeath: true
      permissions:
        - groups.citizens
      home: 5
      home-named: 5
      sethome: 0
      sethome-named: 0
      spawn: 5
      spawn-named: 5
      groupspawn: 5
      homeinvitetp: 5

**Comment by andune** [comment] 2015-02-05 02:29
Is this a duplicate of #33? Can you confirm this is still an issue on the latest build on Jenkins (build 607)?

**Comment by andune** [comment] 2015-02-05 22:45
I believe this issue is a dup of #33, closing it. Please re-open if the fix for #33 didn't fix this for you.

**Closed by andune** 2015-02-05 22:45 UTC
