### ISSUE TITLE
spawnWorldRandom not working anymore

### ISSUE THREAD

**Issue by Xibalba** [andune/HomeSpawnPlus#28] opened 2015-01-22 18:37 UTC
Hi, I'm using HSP since a while now and I particulary like the random spawning feature.

But since I updated HSP to 2.0 beta 1,2 and 3, this stopped working. Now the portals linked with HSP behave like standart portals.

Here are the console logs : http://pastebin.com/XmSWqxtx

We can see that both WorldBorder and MultiversePortals are loading fine, but HSP didn't linked with WorldBorder.

Here are the concerned parts of my config (core and events are separated in two config files) : http://pastebin.com/m400t0mi

So, is it a fail in my config or a bug in HSP ?

Thanks for fixing/helping,
Z3dd7.

**Comment by andune** [comment] 2015-01-23 04:34
Odd that it didn't link with WorldBorder. From your logs I can see v1.8.1 of WorldBorder, I'll download that and give it a test to see why it's not integrating properly.

However, that's a total aside to your actual issue, I think. You say the strategies aren't working at all, which indicates a problem with the portal detection and MultiVerse. I'll recreate a test scenario similar to yours and see if I can get it working or debug what's broken (I know MultiVerse has had a few new revs so maybe the code has changed).

Once we get that working, then WorldBorder integration will become an issue since HSP will just assume a +/- 1000 radius as the messages say. We'll take this one at a time and get the MV integration working first. I'll let you know what I find from my tests.

**Comment by Xibalba** [comment] 2015-01-23 15:36
Ok thanks, tell me if I must test specifical features on my server ;)

**Comment by andune** [comment] 2015-01-23 22:23
Just to keep you updated, from checking I did last night I'm pretty sure this is being caused by a bug where HSP is not picking up the SourcePortal during the Multiverse teleport process.

I will do some more testing later as to why this is happening. It's a good thing if this is an HSP bug since I can easily reproduce the test scenario and that means I have everything I need to fix the problem.

**Comment by andune** [comment] 2015-01-24 02:31
Should be fixed as of build 596 on [Jenkins](http://andune.com/jenkins/job/HomeSpawnPlus/)

**Closed** 2015-01-24 03:13 UTC

**Comment by Xibalba** [comment] 2015-01-24 10:02
Well, with build 598, HSP is noticing MVP but there are still a few errors in console while HSP is trying to  find a safe spot :p

pastebin : http://pastebin.com/7zH7N9cP

**Comment by andune** [comment] 2015-01-24 17:09
Odd. Do you know any details about the teleport that caused this? HSP's safe teleport algorithm works like so:

Given Location x=0,y=40,z=0
1. HSP will check in cocentric cubes around base location looking for a safe spot, up to 10 blocks.
2. If it doesn't find one, it will then check for x=0,z=0,y=[Highest-Y] where [Highest-Y] is Bukkit's call to ".getHighestBlockAt()", the intention being to teleport players to the surface directly above the intended teleport spot if they were teleporting into solid rock.
3. It protects against [Highest-Y] = 0 (for empty worlds) to prevent infinite loop
4. It protects against infinite [Highest-Y] loop by checking to make sure the newly found Highest is actually higher than the loop we just went through.

What is happening in your case is it is infinitely looping around 4. That is, it's not finding a safe location at the original location, HSP then tries to move to [Highest-Y] and check. It's not finding one there either, and somehow is skipping the protection in step 4 to loop again. And again. And again.

I don't know what condition in your world is causing this, so some info would be very helpful in me reproducing the situation and fixing the loop. Right now all the logic checks out to me so this looping should be impossible, yet clearly it's happening on your server somehow.

**Comment by andune** [comment] 2015-01-24 17:12
Do you have maps that are higher than 255 blocks?

**Comment by Xibalba** [comment] 2015-01-24 17:43
I don't know what could be causing this :/

I have 3 portals linked with HSP's spawnWorldRandom on my server : 
* First one is teleporting from main world to nether (now working fine with 598)
* Second one is teleporting from creative world to a random place of this creative world (fine too)
* Third one is teleporting from main world to Freebuild (the buggy one)

Freebuild has nothing special : it's a 5000x5000 map generated in 1.6 using multiverse (here is the MV file for Freebuild : http://pastebin.com/Zcp52gG6) with max height of y=255.

You can view it on the dynmap : http://www.reborn-minecraft.eu:8123/?worldname=Freebuild&mapname=surface&zoom=0&x=804&y=64&z=271

Tell me if you need more info. But what is weird is that HSP was working fine on this map before updating to 2.0..

**Comment by andune** [comment] 2015-01-24 19:42
I've coded a fix in build 599. Give it a try and please report back if you see this error again.

**Comment by Xibalba** [comment] 2015-01-24 22:51
With build 999 the bug seems to be fixed !

Some errors showed up in console once but the player was teleported successfully. Everything went fine with all other tests.

Well thanks for the fix, I'll create some more tickets for other bugs / missing features I noticed since 2.0 :p
